// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTAc9CWQQuOB7PUi2hVtlrL9MEANbFGv4',
    appId: '1:19584522223:web:dd6ba55e8d6b9b3902c81a',
    messagingSenderId: '19584522223',
    projectId: 'inventorymanagement-e3ff7',
    authDomain: 'inventorymanagement-e3ff7.firebaseapp.com',
    storageBucket: 'inventorymanagement-e3ff7.appspot.com',
    measurementId: 'G-3DH3XZRK1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-EfPplD9p-idQ7bSA_Nku8bRCmeun8L8',
    appId: '1:19584522223:android:cd0dbe51be2f637502c81a',
    messagingSenderId: '19584522223',
    projectId: 'inventorymanagement-e3ff7',
    storageBucket: 'inventorymanagement-e3ff7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0OGnjNz7ExptmXr5hH4Bac6QfrgaGwaM',
    appId: '1:19584522223:ios:e4efbb76b17504f902c81a',
    messagingSenderId: '19584522223',
    projectId: 'inventorymanagement-e3ff7',
    storageBucket: 'inventorymanagement-e3ff7.appspot.com',
    iosClientId: '19584522223-pepjk1um0u2dbcrcotipoj5ledt7f680.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0OGnjNz7ExptmXr5hH4Bac6QfrgaGwaM',
    appId: '1:19584522223:ios:a1a0e230675d529602c81a',
    messagingSenderId: '19584522223',
    projectId: 'inventorymanagement-e3ff7',
    storageBucket: 'inventorymanagement-e3ff7.appspot.com',
    iosClientId: '19584522223-e017ulqno5qdq01e7m0fl31dil769r4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
